/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenlab2_tiffannyvarela;

import java.awt.Color;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tiffa
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        computadoras = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_num_serie = new javax.swing.JTextField();
        txt_anio = new javax.swing.JTextField();
        btn_color = new javax.swing.JButton();
        txt_material = new javax.swing.JTextField();
        cmb_ram = new javax.swing.JComboBox<>();
        cmb_dd = new javax.swing.JComboBox<>();
        cmb_vateria = new javax.swing.JComboBox<>();
        cmb_teclado = new javax.swing.JComboBox<>();
        cmb_pantalla = new javax.swing.JComboBox<>();
        cmb_procesador = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        ram = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_agregarram = new javax.swing.JButton();
        txt_marcaram = new javax.swing.JTextField();
        txt_tamram = new javax.swing.JTextField();
        txt_tiemporam = new javax.swing.JTextField();
        disco = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        txt_tamdisco = new javax.swing.JTextField();
        txt_marcadisco = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_tiempodisco = new javax.swing.JTextField();
        btn_agregardisco = new javax.swing.JButton();
        bat = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        txt_materialbat = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_tiempodisco1 = new javax.swing.JTextField();
        btn_agregarbat = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txt_horasbat = new javax.swing.JTextField();
        tec = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        txt_materialtec = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_tiempotec = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        btn_agregartec = new javax.swing.JButton();
        btn_seleccolor = new javax.swing.JButton();
        pant = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btn_agregarpant = new javax.swing.JButton();
        cmb_tactil = new javax.swing.JComboBox<>();
        txt_tipopant = new javax.swing.JTextField();
        txt_tiempopant = new javax.swing.JTextField();
        proce = new javax.swing.JDialog();
        jLabel26 = new javax.swing.JLabel();
        txt_tiempoproce = new javax.swing.JTextField();
        btn_agregarproce = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_velocidadproce = new javax.swing.JTextField();
        txt_nnucleosproce = new javax.swing.JTextField();
        ensamblado = new javax.swing.JDialog();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cmb_computadoras = new javax.swing.JComboBox<>();
        cmb_tecnicos = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_partes = new javax.swing.JTable();
        progr = new javax.swing.JProgressBar();
        btn_iniciar = new javax.swing.JButton();
        listas = new javax.swing.JDialog();
        tecnico = new javax.swing.JDialog();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_edad = new javax.swing.JTextField();
        txt_genero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_tecnicos = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Admin = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        jLabel1.setText("Numero de Serie");

        jLabel2.setText("Año");

        jLabel3.setText("Color");

        jLabel4.setText("Material");

        jLabel5.setText("RAM");

        jLabel6.setText("Disco Duro");

        jLabel7.setText("Bateria");

        jLabel8.setText("Teclado");

        jLabel9.setText("Pantalla");

        jLabel10.setText("Procesador");

        btn_color.setText("Seleccione");
        btn_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_colorActionPerformed(evt);
            }
        });

        cmb_ram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        cmb_dd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        cmb_vateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        cmb_teclado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        cmb_pantalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        cmb_procesador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lista.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(lista);

        jButton4.setText("Cargar Archivo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Crear Archivo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout computadorasLayout = new javax.swing.GroupLayout(computadoras.getContentPane());
        computadoras.getContentPane().setLayout(computadorasLayout);
        computadorasLayout.setHorizontalGroup(
            computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(computadorasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(computadorasLayout.createSequentialGroup()
                        .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_num_serie)
                                .addComponent(txt_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_color, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_material, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                            .addComponent(cmb_ram, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(computadorasLayout.createSequentialGroup()
                        .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(computadorasLayout.createSequentialGroup()
                        .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(computadorasLayout.createSequentialGroup()
                                    .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmb_teclado, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmb_vateria, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap(35, Short.MAX_VALUE))
                                .addGroup(computadorasLayout.createSequentialGroup()
                                    .addComponent(cmb_dd, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(computadorasLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_procesador, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        computadorasLayout.setVerticalGroup(
            computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(computadorasLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(cmb_procesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(computadorasLayout.createSequentialGroup()
                        .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(txt_num_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(txt_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_vateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(btn_color, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_teclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(txt_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmb_ram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(computadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(computadorasLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(computadorasLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))))
        );

        jLabel11.setText("Tamano");

        jLabel12.setText("Marca");

        jLabel13.setText("Tiempo de ensamblaje");

        btn_agregarram.setText("Agregar");
        btn_agregarram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ramLayout = new javax.swing.GroupLayout(ram.getContentPane());
        ram.getContentPane().setLayout(ramLayout);
        ramLayout.setHorizontalGroup(
            ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ramLayout.createSequentialGroup()
                .addGroup(ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ramLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ramLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_tiemporam))
                            .addGroup(ramLayout.createSequentialGroup()
                                .addGroup(ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ramLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_tamram, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ramLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_marcaram, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 24, Short.MAX_VALUE))))
                    .addGroup(ramLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btn_agregarram)))
                .addContainerGap())
        );
        ramLayout.setVerticalGroup(
            ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ramLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_tamram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_marcaram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_tiemporam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btn_agregarram)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel14.setText("Tamano");

        jLabel15.setText("Marca");

        jLabel16.setText("Tiempo de ensamblaje");

        btn_agregardisco.setText("Agregar");
        btn_agregardisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregardiscoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout discoLayout = new javax.swing.GroupLayout(disco.getContentPane());
        disco.getContentPane().setLayout(discoLayout);
        discoLayout.setHorizontalGroup(
            discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discoLayout.createSequentialGroup()
                .addGroup(discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(discoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(discoLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_tiempodisco))
                            .addGroup(discoLayout.createSequentialGroup()
                                .addGroup(discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(discoLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_tamdisco, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(discoLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_marcadisco, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(discoLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btn_agregardisco)))
                .addContainerGap())
        );
        discoLayout.setVerticalGroup(
            discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_tamdisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_marcadisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_tiempodisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btn_agregardisco)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel17.setText("Material");

        jLabel18.setText("Tiempo de ensamblaje");

        btn_agregarbat.setText("Agregar");
        btn_agregarbat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarbatActionPerformed(evt);
            }
        });

        jLabel19.setText("Horas de duracion");

        javax.swing.GroupLayout batLayout = new javax.swing.GroupLayout(bat.getContentPane());
        bat.getContentPane().setLayout(batLayout);
        batLayout.setHorizontalGroup(
            batLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(batLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(batLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(batLayout.createSequentialGroup()
                        .addGroup(batLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(batLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(batLayout.createSequentialGroup()
                                .addComponent(txt_horasbat, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_tiempodisco1)))
                    .addGroup(batLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(37, 37, 37)
                        .addComponent(txt_materialbat, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(batLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(btn_agregarbat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        batLayout.setVerticalGroup(
            batLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(batLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(batLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_horasbat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(batLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_materialbat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(batLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_tiempodisco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btn_agregarbat)
                .addGap(43, 43, 43))
        );

        jLabel20.setText("Material");

        jLabel21.setText("Tiempo de ensamblaje");

        jLabel22.setText("Color");

        btn_agregartec.setText("Agregar");
        btn_agregartec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregartecActionPerformed(evt);
            }
        });

        btn_seleccolor.setText("Seleccione");
        btn_seleccolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccolorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tecLayout = new javax.swing.GroupLayout(tec.getContentPane());
        tec.getContentPane().setLayout(tecLayout);
        tecLayout.setHorizontalGroup(
            tecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tecLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btn_agregartec))
                    .addGroup(tecLayout.createSequentialGroup()
                        .addGroup(tecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tecLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(6, 6, 6)
                                .addComponent(txt_tiempotec))
                            .addGroup(tecLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(37, 37, 37)
                                .addComponent(txt_materialtec, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tecLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(38, 38, 38)
                                .addComponent(btn_seleccolor, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tecLayout.setVerticalGroup(
            tecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tecLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(btn_seleccolor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(tecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txt_materialtec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(tecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_tiempotec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 26, Short.MAX_VALUE)
                .addComponent(btn_agregartec)
                .addGap(26, 26, 26))
        );

        jLabel23.setText("Tactil");

        jLabel24.setText("Tipo");

        jLabel25.setText("Tiempo de ensamblaje");

        btn_agregarpant.setText("Agregar");
        btn_agregarpant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarpantActionPerformed(evt);
            }
        });

        cmb_tactil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Si", "No" }));

        javax.swing.GroupLayout pantLayout = new javax.swing.GroupLayout(pant.getContentPane());
        pant.getContentPane().setLayout(pantLayout);
        pantLayout.setHorizontalGroup(
            pantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantLayout.createSequentialGroup()
                .addGroup(pantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pantLayout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addGap(33, 33, 33)
                                    .addComponent(cmb_tactil, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pantLayout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_tipopant, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pantLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_tiempopant, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pantLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btn_agregarpant)))
                .addGap(20, 20, 20))
        );
        pantLayout.setVerticalGroup(
            pantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel23))
                    .addComponent(cmb_tactil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(pantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txt_tipopant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(pantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txt_tiempopant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btn_agregarpant)
                .addGap(21, 21, 21))
        );

        jLabel26.setText("Tiempo de ensamblaje");

        btn_agregarproce.setText("Agregar");
        btn_agregarproce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarproceActionPerformed(evt);
            }
        });

        jLabel27.setText("Numero de Nucleos");

        jLabel28.setText("Velocidad");

        javax.swing.GroupLayout proceLayout = new javax.swing.GroupLayout(proce.getContentPane());
        proce.getContentPane().setLayout(proceLayout);
        proceLayout.setHorizontalGroup(
            proceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(proceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(proceLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_tiempoproce, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(proceLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(32, 32, 32)
                        .addComponent(txt_nnucleosproce, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(proceLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_velocidadproce, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(proceLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btn_agregarproce, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        proceLayout.setVerticalGroup(
            proceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proceLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(proceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txt_nnucleosproce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(proceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txt_velocidadproce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(proceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txt_tiempoproce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btn_agregarproce)
                .addGap(41, 41, 41))
        );

        jLabel29.setText("Computadoras");

        jLabel30.setText("Tecnicos");

        cmb_computadoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        cmb_tecnicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        tabla_partes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parte", "Tiempo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_partes);

        btn_iniciar.setText("Correr");
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ensambladoLayout = new javax.swing.GroupLayout(ensamblado.getContentPane());
        ensamblado.getContentPane().setLayout(ensambladoLayout);
        ensambladoLayout.setHorizontalGroup(
            ensambladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ensambladoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ensambladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(ensambladoLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(29, 29, 29)
                        .addComponent(cmb_computadoras, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel30)
                        .addGap(50, 50, 50)
                        .addComponent(cmb_tecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addComponent(progr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(ensambladoLayout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(btn_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ensambladoLayout.setVerticalGroup(
            ensambladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ensambladoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(ensambladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(cmb_computadoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_tecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(progr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout listasLayout = new javax.swing.GroupLayout(listas.getContentPane());
        listas.getContentPane().setLayout(listasLayout);
        listasLayout.setHorizontalGroup(
            listasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        listasLayout.setVerticalGroup(
            listasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel31.setText("Nombre");

        jLabel32.setText("Edad");

        jLabel33.setText("Genero");

        lista_tecnicos.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(lista_tecnicos);

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Crear Archivo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Cargar Archivo");

        jButton9.setText("Modificar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tecnicoLayout = new javax.swing.GroupLayout(tecnico.getContentPane());
        tecnico.getContentPane().setLayout(tecnicoLayout);
        tecnicoLayout.setHorizontalGroup(
            tecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tecnicoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(tecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(tecnicoLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tecnicoLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(26, 26, 26)
                        .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tecnicoLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(32, 32, 32)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(112, 112, 112)
                .addGroup(tecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        tecnicoLayout.setVerticalGroup(
            tecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tecnicoLayout.createSequentialGroup()
                .addGroup(tecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tecnicoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(tecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tecnicoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(tecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(tecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tecnicoLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(tecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(txt_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tecnicoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(tecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tecnicoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(tecnicoLayout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Computadores");

        jMenuItem1.setText("Administracion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenu3.setText("Partes");

        jMenuItem2.setText("RAM");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Disco Duro");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Bateria");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Teclado");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Pantalla");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Procesador");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tecnicos");

        Admin.setText("Admin");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        jMenu2.add(Admin);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Orden");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem8.setText("Ensamble");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        computadoras.setModal(true);
        computadoras.pack();
        computadoras.setLocationRelativeTo(this);
        computadoras.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_agregarramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarramActionPerformed
        // TODO add your handling code here:
        try {
            String marca = txt_marcaram.getText();
            double tam = Double.parseDouble(txt_tamram.getText());
            int tiempo = Integer.parseInt(txt_tiemporam.getText());

            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cmb_ram.getModel();
            modelo.addElement(new ram(tam, marca, tiempo));
            cmb_ram.setModel(modelo);
            JOptionPane.showMessageDialog(ram, "Agregado");
            txt_marcaram.setText("");
            txt_tiemporam.setText("");
            txt_tamram.setText("");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(ram, "Error");
        }
    }//GEN-LAST:event_btn_agregarramActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ram.setModal(true);
        ram.pack();
        ram.setLocationRelativeTo(this);
        ram.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btn_agregardiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregardiscoActionPerformed
        // TODO add your handling code here:
        try {
            String marca = txt_marcadisco.getText();
            double tam = Double.parseDouble(txt_tamdisco.getText());
            int tiempo = Integer.parseInt(txt_tiempodisco.getText());

            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cmb_dd.getModel();
            modelo.addElement(new disco(tam, marca, tiempo));
            cmb_dd.setModel(modelo);
            JOptionPane.showMessageDialog(disco, "Agregado");
            txt_marcadisco.setText("");
            txt_tiempodisco.setText("");
            txt_tamdisco.setText("");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(disco, "Error");
        }
    }//GEN-LAST:event_btn_agregardiscoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        disco.setModal(true);
        disco.pack();
        disco.setLocationRelativeTo(this);
        disco.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btn_agregarbatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarbatActionPerformed
        // TODO add your handling code here:
        try {
            String marca = txt_materialbat.getText();
            int horas = Integer.parseInt(txt_horasbat.getText());
            int tiempo = Integer.parseInt(txt_tiempodisco1.getText());

            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cmb_vateria.getModel();
            modelo.addElement(new bateria(horas, marca, tiempo));
            cmb_vateria.setModel(modelo);
            JOptionPane.showMessageDialog(bat, "Agregado");
            txt_materialbat.setText("");
            txt_tiempodisco1.setText("");
            txt_horasbat.setText("");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(bat, "Error");
        }
    }//GEN-LAST:event_btn_agregarbatActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        bat.setModal(true);
        bat.pack();
        bat.setLocationRelativeTo(this);
        bat.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        tec.setModal(true);
        tec.pack();
        tec.setLocationRelativeTo(this);
        tec.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        pant.setModal(true);
        pant.pack();
        pant.setLocationRelativeTo(this);
        pant.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        proce.setModal(true);
        proce.pack();
        proce.setLocationRelativeTo(this);
        proce.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void btn_agregartecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregartecActionPerformed
        // TODO add your handling code here:
        try {
            String material = txt_materialtec.getText();
            Color color = btn_seleccolor.getBackground();
            int tiempo = Integer.parseInt(txt_tiempotec.getText());

            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cmb_teclado.getModel();
            modelo.addElement(new teclado(material, color, tiempo));
            cmb_teclado.setModel(modelo);
            JOptionPane.showMessageDialog(tec, "Agregado");
            txt_materialtec.setText("");
            txt_tiempotec.setText("");
            btn_seleccolor.setBackground(Color.white);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(tec, "Error");
        }
    }//GEN-LAST:event_btn_agregartecActionPerformed

    private void btn_seleccolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccolorActionPerformed
        // TODO add your handling code here:
        btn_seleccolor.setBackground(JColorChooser.showDialog(this, "Seleccione un color", Color.yellow));
    }//GEN-LAST:event_btn_seleccolorActionPerformed

    private void btn_agregarpantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarpantActionPerformed
        // TODO add your handling code here:
        try {
            int opc = cmb_tactil.getSelectedIndex();
            int tiempo = Integer.parseInt(txt_tiempopant.getText());
            String tactil = "";
            String tipo = txt_tipopant.getText();

            if (opc == 1) {
                tactil = "Si";
            }

            if (opc == 2) {
                tactil = "No";
            }
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cmb_pantalla.getModel();
            modelo.addElement(new pantalla(tactil, tipo, tiempo));
            cmb_pantalla.setModel(modelo);
            JOptionPane.showMessageDialog(pant, "Agregado");
            txt_tiempopant.setText("");
            txt_tipopant.setText("");
            cmb_tactil.setSelectedIndex(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(bat, "Error");
        }
    }//GEN-LAST:event_btn_agregarpantActionPerformed

    private void btn_agregarproceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarproceActionPerformed
        // TODO add your handling code here:
        try {
            int num_nucleos = Integer.parseInt(txt_nnucleosproce.getText());
            int tiempo = Integer.parseInt(txt_tiempoproce.getText());
            int velocidad = Integer.parseInt(txt_velocidadproce.getText());

            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cmb_procesador.getModel();
            modelo.addElement(new procesador(num_nucleos, velocidad, tiempo));
            cmb_procesador.setModel(modelo);
            JOptionPane.showMessageDialog(proce, "Agregado");
            txt_nnucleosproce.setText("");
            txt_tiempoproce.setText("");
            txt_velocidadproce.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(proce, "Error");
        }
    }//GEN-LAST:event_btn_agregarproceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            admincompcreadas ac = new admincompcreadas("./computadorasregistradas.txt");
            int num_serie = Integer.parseInt(txt_num_serie.getText());
            int anio = Integer.parseInt(txt_anio.getText());
            String color = String.valueOf(btn_color.getBackground());
            String material = txt_material.getText();
            ram ramm = ((ram) cmb_ram.getSelectedItem());
            disco disco_duro = ((disco) cmb_dd.getSelectedItem());
            bateria batteria = ((bateria) cmb_vateria.getSelectedItem());
            teclado board = ((teclado) cmb_teclado.getSelectedItem());
            pantalla panta = ((pantalla) cmb_pantalla.getSelectedItem());
            procesador proces = ((procesador) cmb_procesador.getSelectedItem());
            DefaultListModel modelo = (DefaultListModel) lista.getModel();
            modelo.addElement(new computadora(num_serie, anio, color, material, ramm, disco_duro, batteria, board, panta, proces));
            lista.setModel(modelo);
            DefaultComboBoxModel mod = (DefaultComboBoxModel) cmb_computadoras.getModel();
            mod.addElement(new computadora(num_serie, anio, color, material, ramm, disco_duro, batteria, board, panta, proces));
            cmb_computadoras.setModel(mod);
            JOptionPane.showMessageDialog(computadoras, "Agregado");
            txt_num_serie.setText("");
            txt_anio.setText("");
            btn_color.setBackground(Color.white);
            txt_material.setText("");
            cmb_ram.setSelectedIndex(0);
            cmb_dd.setSelectedIndex(0);
            cmb_vateria.setSelectedIndex(0);
            cmb_teclado.setSelectedIndex(0);
            cmb_pantalla.setSelectedIndex(0);
            cmb_procesador.setSelectedIndex(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(computadoras, "Error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_colorActionPerformed
        // TODO add your handling code here:
        btn_color.setBackground(JColorChooser.showDialog(this, "Seleccione un color", Color.yellow));
    }//GEN-LAST:event_btn_colorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            int sele = lista.getSelectedIndex();
            DefaultListModel modelo = (DefaultListModel) lista.getModel();
            modelo.remove(sele);
            lista.setModel(modelo);
            
            JOptionPane.showMessageDialog(computadoras, "Eliminado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(computadoras, "Error");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cmb_computadoras.getModel();
        computadora c = (computadora) cmb_computadoras.getSelectedItem();
        int tiempo=0;
        int p1 = c.getRamm().getTiempo();
        int p2 = c.getDisco_duro().getTiempo();
        int p3 = c.getBatteria().getTiempo();
        int p4 = c.getBoard().getTiempo();
        int p5 = c.getPant().getTiempo();
        int p6 = c.getProces().getTiempo();
        int total=p1+p2+p3+p4+p5+p6;
        hilo_proggres hilo;
        hilo=new hilo_proggres(progr, total);
        hilo.start();
//        for (int i = 0; i < 5; i++) {
//            if (i==0) {
//                progr.setMaximum(p1);
//                tiempo =p1;
//                hilo = new hilo_proggres(progr, tiempo);
//            hilo.start();  
//            }
//            if (i==1) {
//                progr.setValue(0);
//                
//                progr.setMaximum(p2);
//                tiempo =p2;
//                hilo = new hilo_proggres(progr, tiempo);
//            hilo.start();  
//            }
//            if (i==2) {
//                progr.setValue(0);
//                progr.setMaximum(p3);
//                tiempo =p3;
//                hilo = new hilo_proggres(progr, tiempo);
//            hilo.start();  
//            }
//            if (i==3) {
//                progr.setValue(0);
//                progr.setMaximum(p4);
//                tiempo =p4;
//                hilo = new hilo_proggres(progr, tiempo);
//            hilo.start();  
//            }
//            if (i==4) {
//                progr.setValue(0);
//                progr.setMaximum(p5);
//                tiempo =p5;
//                hilo = new hilo_proggres(progr, tiempo);
//            hilo.start();  
//            }
//            if (i==5) {
//                progr.setValue(0);
//                System.out.println("final");
//                progr.setMaximum(p6);
//                tiempo =p6;
//                hilo = new hilo_proggres(progr, tiempo);
//            hilo.start();  
//            }
//             
//              
//        }
    }//GEN-LAST:event_btn_iniciarActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        ensamblado.setModal(true);
        ensamblado.pack();
        ensamblado.setLocationRelativeTo(this);
        ensamblado.setVisible(true);
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
         ensamblado.setModal(true);
        ensamblado.pack();
        ensamblado.setLocationRelativeTo(this);
        ensamblado.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            admincompcreadas ac = new admincompcreadas("./computadorascreadas.txt");
            computadora c;
            ArrayList temp = new ArrayList();
            DefaultListModel modelo = (DefaultListModel) lista.getModel();
            modelo.clear();
            try {
                for (int i = 0; i < modelo.getSize(); i++) {
                    //temp.add(i);
                    ac.cargarArchivo();
                    
                    modelo.addElement(ac.getListapersonas().get(i).getNum_serie());
                }
                lista.setModel(modelo);
            } catch (Exception e) {
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            admincompcreadas ac = new admincompcreadas("./computadorascreadas.txt");
        DefaultListModel modelo = (DefaultListModel) lista.getModel();
        
        for (int i = 0; i < modelo.getSize(); i++) {
            ac.getListapersonas().add(((computadora)modelo.get(i)));
            ac.escribirArchivo();
            
        }
        JOptionPane.showMessageDialog(computadoras, "Archivo Creado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(computadoras, "Error");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            String nombre=txt_nombre.getText();
        String genero = txt_genero.getText();
        int exito=0;
        int edad = Integer.parseInt(txt_edad.getText());
        
        tecnicos t = new tecnicos(nombre, edad, genero, exito);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cmb_tecnicos.getModel();
        modelo.addElement(t);
        cmb_tecnicos.setModel(modelo);
        DefaultListModel mod = (DefaultListModel) lista_tecnicos.getModel();
        mod.addElement(t);
        lista_tecnicos.setModel(mod);
        
        txt_nombre.setText("");
        txt_genero.setText("");
        txt_edad.setText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            int sele = lista_tecnicos.getSelectedIndex();
            DefaultListModel modelo = (DefaultListModel) lista_tecnicos.getModel();
            modelo.remove(sele);
            lista_tecnicos.setModel(modelo);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            admintecnico at = new admintecnico("./tecnicos.txt");
        DefaultListModel modelo = (DefaultListModel) lista_tecnicos.getModel();
        
        for (int i = 0; i < modelo.getSize(); i++) {
            at.getListapersonas().add(((tecnicos)modelo.get(i)));
            at.escribirArchivo();
        }
        modelo.clear();
        JOptionPane.showMessageDialog(tecnico, "Archivo Creado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(tecnico, "Error");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        // TODO add your handling code here:
        tecnico.setModal(true);
        tecnico.pack();
        tecnico.setLocationRelativeTo(this);
        tecnico.setVisible(true);
    }//GEN-LAST:event_AdminActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int selec = lista_tecnicos.getSelectedIndex();
        DefaultListModel model = (DefaultListModel) lista_tecnicos.getModel();
        txt_nombre.setText(((tecnicos)model.get(selec)).getNombre());
        txt_edad.setText(Integer.toString(((tecnicos)model.get(selec)).getEdad()));
        txt_genero.setText(((tecnicos)model.get(selec)).getGenero());
        model.remove(selec);
        lista_tecnicos.setModel(model);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
hilo_proggres hp;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Admin;
    private javax.swing.JDialog bat;
    private javax.swing.JButton btn_agregarbat;
    private javax.swing.JButton btn_agregardisco;
    private javax.swing.JButton btn_agregarpant;
    private javax.swing.JButton btn_agregarproce;
    private javax.swing.JButton btn_agregarram;
    private javax.swing.JButton btn_agregartec;
    private javax.swing.JButton btn_color;
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JButton btn_seleccolor;
    private javax.swing.JComboBox<String> cmb_computadoras;
    private javax.swing.JComboBox<String> cmb_dd;
    private javax.swing.JComboBox<String> cmb_pantalla;
    private javax.swing.JComboBox<String> cmb_procesador;
    private javax.swing.JComboBox<String> cmb_ram;
    private javax.swing.JComboBox<String> cmb_tactil;
    private javax.swing.JComboBox<String> cmb_teclado;
    private javax.swing.JComboBox<String> cmb_tecnicos;
    private javax.swing.JComboBox<String> cmb_vateria;
    private javax.swing.JDialog computadoras;
    private javax.swing.JDialog disco;
    private javax.swing.JDialog ensamblado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lista;
    private javax.swing.JList<String> lista_tecnicos;
    private javax.swing.JDialog listas;
    private javax.swing.JDialog pant;
    private javax.swing.JDialog proce;
    private javax.swing.JProgressBar progr;
    private javax.swing.JDialog ram;
    private javax.swing.JTable tabla_partes;
    private javax.swing.JDialog tec;
    private javax.swing.JDialog tecnico;
    private javax.swing.JTextField txt_anio;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_genero;
    private javax.swing.JTextField txt_horasbat;
    private javax.swing.JTextField txt_marcadisco;
    private javax.swing.JTextField txt_marcaram;
    private javax.swing.JTextField txt_material;
    private javax.swing.JTextField txt_materialbat;
    private javax.swing.JTextField txt_materialtec;
    private javax.swing.JTextField txt_nnucleosproce;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_num_serie;
    private javax.swing.JTextField txt_tamdisco;
    private javax.swing.JTextField txt_tamram;
    private javax.swing.JTextField txt_tiempodisco;
    private javax.swing.JTextField txt_tiempodisco1;
    private javax.swing.JTextField txt_tiempopant;
    private javax.swing.JTextField txt_tiempoproce;
    private javax.swing.JTextField txt_tiemporam;
    private javax.swing.JTextField txt_tiempotec;
    private javax.swing.JTextField txt_tipopant;
    private javax.swing.JTextField txt_velocidadproce;
    // End of variables declaration//GEN-END:variables
}
